# Generated by Django 5.0.6 on 2024-07-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
