# Generated by Django 5.0.6 on 2024-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(choices=[('Куртка', 'Куртка'), ('Шуба', 'Шуба'), ('Шапка', 'Шапка')], default='Куртка', max_length=20),
        ),
    ]
