# Generated by Django 5.0.6 on 2024-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_clothing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(choices=[('Шубы и меха', 'Шубы и меха'), ('Кожаные куртки', 'Кожаные куртки'), ('Плащи и тренчи', 'Плащи и тренчи'), ('Демисезонные куртки', 'Демисезонные куртки'), ('Пуховики и зимние куртки', 'Пуховики и зимние куртки'), ('Пальто', 'Пальто'), ('Шубы из овчины', 'Шубы из овчины'), ('Зимние кожаные куртки', 'Зимние кожаные куртки'), ('Дубленки', 'Дубленки'), ('Экошубы', 'Экошубы')], default='Куртка', max_length=100),
        ),
    ]
