# Generated by Django 5.0.6 on 2024-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_type_alter_product_clothing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(choices=[('Шубы и меха', 'Шубы и меха'), ('Кожаные куртки', 'Кожаные куртки'), ('Плащи и тренчи', 'Плащи и тренчи'), ('Демисезонные куртки', 'Демисезонные куртки'), ('Пуховики и зимние куртки', 'Пуховики и зимние куртки'), ('Пальто', 'Пальто'), ('Шубы из овчины', 'Шубы из овчины'), ('Зимние кожаные куртки', 'Зимние кожаные куртки'), ('Дубленки', 'Дубленки'), ('Экошубы', 'Экошубы'), ('Сумки и рюкзаки', 'Сумки и рюкзаки'), ('Кошельки и обложки', 'Кошельки и обложки'), ('Платки и шарфы', 'Платки и шарфы'), ('Перчатки', 'Перчатки'), ('Головные уборы', 'Головные уборы'), ('Зонты', 'Зонты')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Верхняя одежда', 'Верхняя одежда'), ('Аксессуар', 'Аксессуар')], default='Верхняя одежда', max_length=100),
        ),
    ]
